### ISSUE TITLE
Could your provide a deploy prototxt?

### ISSUE THREAD

**Issue by xhzcyc** [wuqianliang/deepid2_caffe#1]
Thanks for your sharing!
Could your provide a deploy prototxt?

**Comment by wuqianliang** [comment]
deploy prototxt will commit next week, I am working on it .

**Comment by wuqianliang** [comment]
@xhzcyc  try it 
 https://github.com/wuqianliang/deepid2_caffe/blob/master/caffe_master/examples/deepid2/DeepID2_deploy.prototxt

I will try it on Ms Celeb 1M dataset next week.

**Comment by xhzcyc** [comment]
@wuqianliang 
Thanks very much!
