### ISSUE TITLE
Training LFW

### ISSUE THREAD

**Issue by xhzcyc** [wuqianliang/deepid2_caffe#3]
I have tried your training script, but it does't work!
assert "check failed: data_"

Thanks

**Comment by wuqianliang** [comment]
@xhzcyc  Do you have the train.txt and val.txt  in lfw-images  dir， you can generate them using train_test_data_split.py

**Comment by xhzcyc** [comment]
I did liked you said, but running create_DeepID2.sh, assert "A total of 0 images"!
Did you encounter this problem?

**Comment by wuqianliang** [comment]
@xhzcyc    assert "A total of 0 images"   --  you may not have train.txt  and val.txt  in caffe-master/data/lfw  dir, you should use   train_test_data_split.py  to generate theses two files.

**Comment by xhzcyc** [comment]
I have found the problem. The caffe need to modify in convert_imageset()!
I succeed in test the model on LFW!
Could you share your MsCeleb dataset?
Thanks
